/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.paint;

import com.paint.shape.Shape;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.awt.event.HierarchyBoundsListener;
import java.util.Vector;
import java.util.logging.Logger;
import javax.swing.JColorChooser;

/**
 *
 * @author eltntawy
 */
public class Paint extends java.applet.Applet implements ActionListener {

    /**
     * Initializes the applet Paint
     */
    private Graphics graphics;
    private int shapesCount;
    Vector<Shape> shapesVector = new Vector<Shape>();

    private static final Logger LOG = Logger.getGlobal();

    public void init() {
        
        
        
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    setSize(1024, 800);
                    graphics = drawPanel.getGraphics();
                    drawPanel.setBackground(Color.white);
                    System.out.println(getClass().getClassLoader().getResource("logging.properties"));
                    System.out.println("LOG.getResourceBundleName(); " + LOG.getResourceBundleName());
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        colorPanel = new javax.swing.JPanel();
        btnColor1 = new java.awt.Button();
        btnColor2 = new java.awt.Button();
        btnColor3 = new java.awt.Button();
        btnColor4 = new java.awt.Button();
        btnColor5 = new java.awt.Button();
        btnColor6 = new java.awt.Button();
        btnColor7 = new java.awt.Button();
        btnColor8 = new java.awt.Button();
        btnColor9 = new java.awt.Button();
        btnColor10 = new java.awt.Button();
        btnColor11 = new java.awt.Button();
        btnColor12 = new java.awt.Button();
        btnColor13 = new java.awt.Button();
        btnColor14 = new java.awt.Button();
        btnColor15 = new java.awt.Button();
        btnColor = new java.awt.Button();
        shapPanel = new javax.swing.JPanel();
        btnDrawCircle = new java.awt.Button();
        btnDrawRect = new java.awt.Button();
        btnDrawLine = new java.awt.Button();
        btnDrawFree = new java.awt.Button();
        btnEarse = new java.awt.Button();
        chboxIsSold = new java.awt.Checkbox();
        btnUndo = new java.awt.Button();
        btnRedo = new java.awt.Button();
        panel1 = new java.awt.Panel();
        paintPanel = new javax.swing.JPanel();
        drawPanel = new java.awt.Panel();

        setLayout(new java.awt.BorderLayout());

        toolPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toolPanel.setMaximumSize(new java.awt.Dimension(200, 400));
        toolPanel.setMinimumSize(new java.awt.Dimension(200, 400));
        toolPanel.setPreferredSize(new java.awt.Dimension(140, 400));

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolBar1.setDoubleBuffered(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(150, 300));
        jToolBar1.setMinimumSize(new java.awt.Dimension(130, 300));
        jToolBar1.setPreferredSize(new java.awt.Dimension(130, 500));

        colorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));
        colorPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        colorPanel.setMaximumSize(new java.awt.Dimension(140, 220));
        colorPanel.setMinimumSize(new java.awt.Dimension(140, 220));
        colorPanel.setPreferredSize(new java.awt.Dimension(140, 220));

        btnColor1.setBackground(java.awt.Color.white);
        btnColor1.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor1.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor1.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor1.addActionListener(this);
        colorPanel.add(btnColor1);

        btnColor2.setBackground(java.awt.Color.lightGray);
        btnColor2.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor2.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor2.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor2.addActionListener(this);
        colorPanel.add(btnColor2);

        btnColor3.setBackground(java.awt.Color.gray);
        btnColor3.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor3.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor3.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor3.addActionListener(this);
        colorPanel.add(btnColor3);

        btnColor4.setBackground(java.awt.Color.darkGray);
        btnColor4.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor4.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor4.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor4.addActionListener(this);
        colorPanel.add(btnColor4);

        btnColor5.setBackground(java.awt.Color.black);
        btnColor5.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor5.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor5.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor5.addActionListener(this);
        colorPanel.add(btnColor5);

        btnColor6.setBackground(java.awt.Color.red);
        btnColor6.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor6.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor6.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor6.addActionListener(this);
        colorPanel.add(btnColor6);

        btnColor7.setBackground(java.awt.Color.pink);
        btnColor7.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor7.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor7.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor7.addActionListener(this);
        colorPanel.add(btnColor7);

        btnColor8.setBackground(java.awt.Color.orange);
        btnColor8.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor8.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor8.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor8.addActionListener(this);
        colorPanel.add(btnColor8);

        btnColor9.setBackground(java.awt.Color.yellow);
        btnColor9.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor9.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor9.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor9.addActionListener(this);
        colorPanel.add(btnColor9);

        btnColor10.setBackground(java.awt.Color.green);
        btnColor10.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor10.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor10.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor10.addActionListener(this);
        colorPanel.add(btnColor10);

        btnColor11.setBackground(java.awt.Color.magenta);
        btnColor11.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor11.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor11.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor11.addActionListener(this);
        colorPanel.add(btnColor11);

        btnColor12.setBackground(java.awt.Color.cyan);
        btnColor12.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor12.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor12.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor12.addActionListener(this);
        colorPanel.add(btnColor12);

        btnColor13.setBackground(java.awt.Color.blue);
        btnColor13.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor13.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor13.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor13.addActionListener(this);
        colorPanel.add(btnColor13);

        btnColor14.setBackground(new java.awt.Color(0, 0, 102));
        btnColor14.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor14.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor14.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor14.addActionListener(this);
        colorPanel.add(btnColor14);

        btnColor15.setBackground(new java.awt.Color(102, 0, 0));
        btnColor15.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor15.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor15.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor15.addActionListener(this);
        colorPanel.add(btnColor15);

        btnColor.setBackground(new java.awt.Color(0, 0, 0));
        btnColor.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColor.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColor.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColor.addActionListener(this);
        colorPanel.add(btnColor);

        jToolBar1.add(colorPanel);

        shapPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tools"));
        shapPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shapPanel.setMaximumSize(new java.awt.Dimension(200, 200));
        shapPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        shapPanel.setPreferredSize(new java.awt.Dimension(200, 200));

        btnDrawCircle.setLabel("Circle");
        btnDrawCircle.setMaximumSize(new java.awt.Dimension(50, 25));
        btnDrawCircle.setMinimumSize(new java.awt.Dimension(50, 25));
        btnDrawCircle.addActionListener(this);
        shapPanel.add(btnDrawCircle);

        btnDrawRect.setLabel("Rect");
        btnDrawRect.setMaximumSize(new java.awt.Dimension(50, 25));
        btnDrawRect.setMinimumSize(new java.awt.Dimension(50, 25));
        btnDrawRect.addActionListener(this);
        shapPanel.add(btnDrawRect);

        btnDrawLine.setLabel("Line");
        btnDrawLine.setMaximumSize(new java.awt.Dimension(50, 25));
        btnDrawLine.setMinimumSize(new java.awt.Dimension(50, 25));
        btnDrawLine.addActionListener(this);
        shapPanel.add(btnDrawLine);

        btnDrawFree.setLabel("Pin");
        btnDrawFree.setMaximumSize(new java.awt.Dimension(50, 25));
        btnDrawFree.setMinimumSize(new java.awt.Dimension(50, 25));
        btnDrawFree.addActionListener(this);
        shapPanel.add(btnDrawFree);

        btnEarse.setActionCommand("Earse");
        btnEarse.setLabel("Earse");
        btnEarse.setMaximumSize(new java.awt.Dimension(50, 25));
        btnEarse.setMinimumSize(new java.awt.Dimension(50, 25));
        btnEarse.addActionListener(this);
        shapPanel.add(btnEarse);

        chboxIsSold.setLabel("Sold");
        chboxIsSold.setMaximumSize(new java.awt.Dimension(50, 25));
        chboxIsSold.setMinimumSize(new java.awt.Dimension(50, 25));
        shapPanel.add(chboxIsSold);

        btnUndo.setActionCommand("Undo");
        btnUndo.setLabel("Undo");
        btnUndo.setMaximumSize(new java.awt.Dimension(50, 25));
        btnUndo.setMinimumSize(new java.awt.Dimension(50, 25));
        btnUndo.addActionListener(this);
        shapPanel.add(btnUndo);

        btnRedo.setActionCommand("Redo");
        btnRedo.setLabel("Redo");
        btnRedo.setMaximumSize(new java.awt.Dimension(50, 25));
        btnRedo.setMinimumSize(new java.awt.Dimension(50, 25));
        btnRedo.setName("Redo"); // NOI18N
        btnRedo.addActionListener(this);
        shapPanel.add(btnRedo);

        jToolBar1.add(shapPanel);
        jToolBar1.add(panel1);

        toolPanel.add(jToolBar1);

        add(toolPanel, java.awt.BorderLayout.WEST);

        paintPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Drawing Area"));
        paintPanel.setLayout(new java.awt.BorderLayout());

        drawPanel.setBackground(new java.awt.Color(255, 255, 255));
        paintPanel.add(drawPanel, java.awt.BorderLayout.CENTER);

        add(paintPanel, java.awt.BorderLayout.CENTER);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == btnColor1) {
            Paint.this.btnColorAction(evt);
            Paint.this.btnDrawAction(evt);
        }
        else if (evt.getSource() == btnColor2) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor3) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor4) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor5) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor6) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor7) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor8) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor9) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor10) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor11) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor12) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor13) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor14) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor15) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnColor) {
            Paint.this.btnColorAction(evt);
        }
        else if (evt.getSource() == btnDrawCircle) {
            Paint.this.btnDrawAction(evt);
        }
        else if (evt.getSource() == btnDrawRect) {
            Paint.this.btnDrawAction(evt);
        }
        else if (evt.getSource() == btnDrawLine) {
            Paint.this.btnDrawAction(evt);
        }
        else if (evt.getSource() == btnDrawFree) {
            Paint.this.btnDrawAction(evt);
        }
        else if (evt.getSource() == btnEarse) {
            Paint.this.btnDrawAction(evt);
        }
        else if (evt.getSource() == btnUndo) {
            Paint.this.btnDrawAction(evt);
        }
        else if (evt.getSource() == btnRedo) {
            Paint.this.btnDrawAction(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorAction
        // TODO add your handling code here:
        if (evt.getSource() == btnColor1) {
            btnColor.setBackground(btnColor1.getBackground());
        } else if (evt.getSource() == btnColor2) {
            btnColor.setBackground(btnColor2.getBackground());
        } else if (evt.getSource() == btnColor3) {
            btnColor.setBackground(btnColor3.getBackground());
        } else if (evt.getSource() == btnColor4) {
            btnColor.setBackground(btnColor4.getBackground());
        } else if (evt.getSource() == btnColor5) {
            btnColor.setBackground(btnColor5.getBackground());
        } else if (evt.getSource() == btnColor6) {
            btnColor.setBackground(btnColor6.getBackground());
        } else if (evt.getSource() == btnColor7) {
            btnColor.setBackground(btnColor7.getBackground());
        } else if (evt.getSource() == btnColor8) {
            btnColor.setBackground(btnColor8.getBackground());
        } else if (evt.getSource() == btnColor9) {
            btnColor.setBackground(btnColor9.getBackground());
        } else if (evt.getSource() == btnColor10) {
            btnColor.setBackground(btnColor10.getBackground());
        } else if (evt.getSource() == btnColor11) {
            btnColor.setBackground(btnColor11.getBackground());
        } else if (evt.getSource() == btnColor12) {
            btnColor.setBackground(btnColor12.getBackground());
        } else if (evt.getSource() == btnColor13) {
            btnColor.setBackground(btnColor13.getBackground());
        } else if (evt.getSource() == btnColor14) {
            btnColor.setBackground(btnColor14.getBackground());
        } else if (evt.getSource() == btnColor15) {
            btnColor.setBackground(btnColor15.getBackground());
        } else if (evt.getSource() == btnColor) {
            Color color = JColorChooser.showDialog(this, "Choose your color", btnColor.getBackground());
            if(color != null)
                btnColor.setBackground(color);
        }
    }//GEN-LAST:event_btnColorAction

    private void btnDrawAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawAction
        // TODO add your handling code here:
        if (evt.getSource() == btnDrawCircle) {
            drawRondomStringOnPanel("btnDrawCircle");
        } else if (evt.getSource() == btnDrawRect) {
            drawRondomStringOnPanel("btnDrawRect");
        } else if (evt.getSource() == btnDrawLine) {
            drawRondomStringOnPanel("btnDrawLine");
        } else if (evt.getSource() == btnDrawFree) {
            drawRondomStringOnPanel("btnDrawFree");
        } else if (evt.getSource() == btnEarse) {
            drawRondomStringOnPanel("btnEarse");
        } else if (evt.getSource() == btnUndo) {
            drawRondomStringOnPanel("btnUndo");
        } else if (evt.getSource() == btnRedo) {
            drawRondomStringOnPanel("btnRedo");
        }

    }//GEN-LAST:event_btnDrawAction


    private void drawRondomStringOnPanel(String s) {

        graphics.setColor(btnColor.getBackground());
        graphics.setPaintMode();
        graphics.drawString(s, (1 + (int) (Math.random() * 600)), (1 + (int) (Math.random() * 600)));
        drawPanel.paint(graphics);

        // paint(graphics);
    }

    public void paintShapes() {
        
        for(Shape s : shapesVector) {
            s.draw(graphics);
        }
        
    }

    // <editor-fold defaultstate="collapsed" desc="Applet Repaint">
    @Override
    public void repaint() {
        super.repaint();
        paintShapes();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        paintShapes();
    }
    //</editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Class Member">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnColor;
    private java.awt.Button btnColor1;
    private java.awt.Button btnColor10;
    private java.awt.Button btnColor11;
    private java.awt.Button btnColor12;
    private java.awt.Button btnColor13;
    private java.awt.Button btnColor14;
    private java.awt.Button btnColor15;
    private java.awt.Button btnColor2;
    private java.awt.Button btnColor3;
    private java.awt.Button btnColor4;
    private java.awt.Button btnColor5;
    private java.awt.Button btnColor6;
    private java.awt.Button btnColor7;
    private java.awt.Button btnColor8;
    private java.awt.Button btnColor9;
    private java.awt.Button btnDrawCircle;
    private java.awt.Button btnDrawFree;
    private java.awt.Button btnDrawLine;
    private java.awt.Button btnDrawRect;
    private java.awt.Button btnEarse;
    private java.awt.Button btnRedo;
    private java.awt.Button btnUndo;
    private java.awt.Checkbox chboxIsSold;
    private javax.swing.JPanel colorPanel;
    private java.awt.Panel drawPanel;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel paintPanel;
    private java.awt.Panel panel1;
    private javax.swing.JPanel shapPanel;
    private javax.swing.JPanel toolPanel;
    // End of variables declaration//GEN-END:variables
// </editor-fold>
}
